export const hotelData = [
    {
      name: 'Burj Al Arab',
      city: 'Dubai',
      country: 'United Arab Emirates',
      lat: 25.1412,
      lng: 55.1854,
      image: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/2f/3e/3f/burj-al-arab.jpg?w=300&h=200&s=1',
      description: 'Iconic sail‑shaped luxury hotel with exceptional service.',
      rating: 4.9,
      reviews: 6389,
      price: '$600/night',
    },
    {
      name: 'The Ritz Paris',
      city: 'Paris',
      country: 'France',
      lat: 48.8682,
      lng: 2.3297,
      image: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/17/15/6d/d6/paris.jpg?w=300&h=300&s=1',
      description: 'Historic luxury hotel in the heart of Paris.',
      rating: 4.8,
      reviews: 4256,
      price: '$950/night',
    },
    {
      name: 'Bellagio Hotel & Casino',
      city: 'Las Vegas',
      country: 'USA',
      lat: 36.1129,
      lng: -115.1765,
      image: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2a/34/2d/28/caption.jpg?w=300&h=300&s=1',
      description: 'Iconic Vegas hotel with famous fountain show.',
      rating: 4.7,
      reviews: 8934,
      price: '$299/night',
    },
    {
      name: 'The Savoy',
      city: 'London',
      country: 'UK',
      lat: 51.5105,
      lng: -0.1204,
      image: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0d/af/70/3c/the-white-tower-the-norman.jpg?w=300&h=-1&s=1',
      description: 'Historic luxury hotel on the River Thames.',
      rating: 4.8,
      reviews: 5642,
      price: '$450/night',
    },
    {
      name: 'Hotel Degli Orafi',
      city: 'Florence',
      country: 'Italy',
      lat: 43.7679,
      lng: 11.2531,
      image: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/33/dc/8a/caption.jpg?w=300&h=300&s=1',
      description: 'Elegant hotel with stunning views of Ponte Vecchio.',
      rating: 4.6,
      reviews: 2317,
      price: '$320/night',
    },
    {
      name: 'The Plaza',
      city: 'New York City',
      country: 'USA',
      lat: 40.7645,
      lng: -73.9741,
      image: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/c5/7c/68/caption.jpg?w=300&h=300&s=1',
      description: 'Landmark luxury hotel at the corner of Central Park.',
      rating: 4.7,
      reviews: 7423,
      price: '$595/night',
    },
    {
      name: 'Hotel Arts Barcelona',
      city: 'Barcelona',
      country: 'Spain',
      lat: 41.3870,
      lng: 2.1946,
      image: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/ae/5d/da/caption.jpg?w=300&h=300&s=1',
      description: 'Beachfront luxury hotel with stunning sea views.',
      rating: 4.6,
      reviews: 3879,
      price: '$350/night',
    },
    {
      name: 'Colosseum Luxury Hotel',
      city: 'Rome',
      country: 'Italy',
      lat: 41.8902,
      lng: 12.4924,
      image: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/c9/6c/08/caption.jpg?w=300&h=300&s=1',
      description: 'Elegant hotel near Rome\'s historic center.',
      rating: 4.5,
      reviews: 2954,
      price: '$280/night',
    },
    {
      name: 'The Oberoi Grand',
      city: 'Kolkata',
      country: 'India',
      lat: 22.5654,
      lng: 88.3525,
      image: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/3d/6b/0d/caption.jpg?w=300&h=300&s=1',
      description: 'Heritage luxury hotel in the heart of Kolkata.',
      rating: 4.8,
      reviews: 2189,
      price: '$220/night',
    },
    {
      name: 'Raffles Hotel',
      city: 'Singapore',
      country: 'Singapore',
      lat: 1.2950,
      lng: 103.8538,
      image: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/21/4d/63/31/caption.jpg?w=300&h=300&s=1',
      description: 'Colonial-style icon known for the Singapore Sling cocktail.',
      rating: 4.9,
      reviews: 4532,
      price: '$550/night',
    },
    {
      name: 'Four Seasons Reykjavik',
      city: 'Reykjavik',
      country: 'Iceland',
      lat: 64.1466,
      lng: -21.9426,
      image: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/27/84/4d/17/caption.jpg?w=300&h=300&s=1',
      description: 'Modern luxury hotel with views of the Northern Lights.',
      rating: 4.7,
      reviews: 1876,
      price: '$420/night',
    },
    {
      name: 'Eichardt\'s Private Hotel',
      city: 'Queenstown',
      country: 'New Zealand',
      lat: -45.0323,
      lng: 168.6608,
      image: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/33/fb/29/caption.jpg?w=300&h=300&s=1',
      description: 'Boutique luxury lodging on Lake Wakatipu.',
      rating: 4.8,
      reviews: 943,
      price: '$680/night',
    },
    {
      name: 'Park Hyatt Siem Reap',
      city: 'Siem Reap',
      country: 'Cambodia',
      lat: 13.3555,
      lng: 103.8555,
      image: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/c5/c8/5d/caption.jpg?w=300&h=300&s=1',
      description: 'Luxury hotel near the ancient temples of Angkor Wat.',
      rating: 4.7,
      reviews: 1531,
      price: '$190/night',
    },
    {
      name: 'Taj Mahal Palace',
      city: 'Mumbai',
      country: 'India',
      lat: 18.9220,
      lng: 72.8347,
      image: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1a/8d/ea/26/caption.jpg?w=300&h=300&s=1',
      description: 'Historic luxury hotel overlooking the Arabian Sea.',
      rating: 4.8,
      reviews: 5321,
      price: '$310/night',
    },
    {
      name: 'Cox\'s Bazar Beach Resort',
      city: 'Cox\'s Bazar',
      country: 'Bangladesh',
      lat: 21.4272,
      lng: 91.9702,
      image: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/10/e2/f8/43/longest-sea-beach-in.jpg?w=300&h=300&s=1',
      description: 'Beachfront resort on the world\'s longest natural sandy beach.',
      rating: 4.3,
      reviews: 876,
      price: '$120/night',
    },
    {
      name: 'Mayfair Lagoon',
      city: 'Puri',
      country: 'India',
      lat: 19.8135,
      lng: 85.8314,
      image: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/09/ee/11/39/new-marine-drive-puri.jpg?w=300&h=300&s=1',
      description: 'Luxury beach resort with traditional Odisha architecture.',
      rating: 4.4,
      reviews: 1245,
      price: '$160/night',
    },
    {
      name: 'Mandarmani Beach Resort',
      city: 'Mandarmani',
      country: 'India',
      lat: 21.6757,
      lng: 87.6907,
      image: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0f/19/c7/ab/dsc-0011-2-largejpg.jpg?w=300&h=300&s=1',
      description: 'Seaside resort with private beach access.',
      rating: 4.2,
      reviews: 891,
      price: '$95/night',
    },
    {
      name: 'Digha Seaside Resort',
      city: 'Digha',
      country: 'India',
      lat: 21.6260,
      lng: 87.5059,
      image: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/08/f1/a7/e7/the-sea-beach-at-old.jpg?w=300&h=300&s=1',
      description: 'Family-friendly beach resort on the Bay of Bengal.',
      rating: 4.1,
      reviews: 724,
      price: '$85/night',
    }
  ];